[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
evm_version = "cancun"
auto_detect_remappings = false
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/oz-contracts-v5/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/oz-contracts-upgradeable-v5/contracts/",
  "@solmate/=lib/boring-vault/lib/solmate/src/"
]

[lint]
ignore = ["lib/**"]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
